/// A library for handling conversions between objects and `Map` values.
///
/// Contains support for using type data generated by:
///   * [built_value](https://pub.dev/packages/built_value)
///   * [protobuf](https://pub.dev/packages/protobuf)
library database.mapper;

export 'src/mapper/built_value_mapper.dart';
export 'src/mapper/mapper.dart';
export 'src/mapper/protobuf_mapper.dart';
